uswest1:
  hosts:
    slave1:
      ansible_host: 10.138.0.23
      tags:
        - slave1
    slave2:
      ansible_host: 10.138.0.25
      tags:
        - slave2
  vars:
    ansible_user: anish
    ansible_python_interpreter: /usr/bin/python3