uswest1:
        hosts:
                slave1:
                        ansible_host: 10.138.0.23
                slave2:
                        ansible_host: 10.138.0.25
        vars:
                ansible_user: anish
                ansible_python_interpreter: /usr/bin/python3
