uswest1:
        hosts:
                slave1:
                slave2:
        vars:
                ansible_user: anish
                ansible_host: 10.138.0.22
                ansible_python_interpreter: /usr/bin/python3
