- hosts: all
  become: 'yes'
  vars:
          user:
                  - name: "anish"
          packages:
                  - htop
                  - strace
                  - lsof
  tasks:
          - name: Install the list of packages
            apt:
                    name: "{{ packages }}"
                    state: present
          - name: All done!
            debug:
                    msg: All packages installed successfully
